name: project_ngo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  flutter_webview_plugin: ^0.4.0
  geolocator: ^9.0.2
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.0
  path_provider: ^2.1.1
  pdf: ^3.10.4
  permission_handler: ^10.4.3
  printing: ^5.11.0
  syncfusion_flutter_calendar: ^22.1.37
  syncfusion_flutter_charts: ^22.1.37
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/images/
